# Generated by Django 4.2.2 on 2023-06-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('desc', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=400)),
            ],
        ),
    ]
